name: Build and deploy Python app to Azure Web App - chad-automation-station

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'

      - name: Create and start virtual environment
        run: |
          python -m venv antenv
          source antenv/bin/activate

      - name: Install dependencies
        run: |
          source antenv/bin/activate
          pip install -r requirements.txt
          pip install gunicorn

      - name: Run collectstatic
        env:
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_PORT: ${{ secrets.DB_PORT }}
          DJANGO_SETTINGS_MODULE: automation_station_project.settings
        run: |
          source antenv/bin/activate
          cd automation_station_project
          python manage.py collectstatic --noinput

      - name: Zip artifact for deployment
        run: |
          zip -r release.zip ./* -x "antenv/*"

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: Set up Python environment
        run: |
          python -m venv antenv
          source antenv/bin/activate
          pip install -r requirements.txt
          pip install gunicorn

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'chad-automation-station'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_A43D4D4FB7E2468196F5531E7332E324 }}
        env:
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_PORT: ${{ secrets.DB_PORT }}
          DJANGO_SETTINGS_MODULE: automation_station_project.settings

      - name: Run Gunicorn
        run: |
          source antenv/bin/activate
          gunicorn --bind=0.0.0.0:8000 --timeout 600 automation_station_project.wsgi:application
